# Generated by Django 5.1.3 on 2025-02-13 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='learnings',
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.project'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='paragraph',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learning',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.project'),
        ),
    ]
