# Generated by Django 5.1.3 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_features_remove_project_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.CharField(default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='time_to_read',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
