# Generated by Django 5.1.3 on 2025-02-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_faq_options_faq_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Job', 'Job'), ('Tech', 'Tech'), ('Freelance', 'Freelance'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
