# Generated by Django 5.1.3 on 2025-02-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pdf',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
    ]
