# Generated by Django 5.1.3 on 2025-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pdf_resume_file_remove_resume_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='categories',
            field=models.CharField(default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AddField(
            model_name='faq',
            name='categories',
            field=models.CharField(default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.CharField(default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload a certificate image, PDF, or DOC file', null=True, upload_to='skills/certificates/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resource_links',
            field=models.TextField(blank=True, help_text='Enter resource links separated by commas (YouTube, PDFs, Docs, Images)'),
        ),
    ]
