# Generated by Django 5.2.7 on 2026-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_blog_categories_alter_blog_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Sender IP address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publication_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="publication_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.PositiveIntegerField(db_index=True, default=50),
        ),
    ]
