# Generated by Django 5.2.7 on 2026-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_contactmessage_ip_address_alter_blog_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="resume",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Leave blank to auto-fetch from free developer icon libraries (Devicon / SimpleIcons / SkillIcons), or upload your own.",
                null=True,
                upload_to="skills/icons/",
            ),
        ),
    ]
